version: '3'
services:
  web:
   container_name: mybrcollection_web
   build:
     context: ./movie-service
     dockerfile: Dockerfile
   depends_on:
     - mysql
   volumes:
     - /data/spring-boot-app
   ports:
    - 8080:8080
   restart: on-failure

  mysql:
   image: mysql:5.7
   container_name: mybrcollection_mysql
   environment:
     MYSQL_DATABASE: mybrcollection
     MYSQL_ROOT_PASSWORD: root12345
     MYSQL_USER: matteo
     MYSQL_PASSWORD: br12345
   volumes:
    - /data/mysql

  ui:
   container_name: mybrcollection_ui
   build:
     context: ./ui-service
     dockerfile: Dockerfile
   ports:
    - 8079:80 
